# Import Library

In [3]:
# import pickle = sudah mencoba menggunakan pickel tapi datanya tidak bisa di load 
import numpy as np # numpy (diimpor sebagai np): NumPy digunakan untuk mengubah data kategorial menjadi numerik. Numpy juga digunakan untuk komputasi, komputasi numerik, aljabar linear, dan pembangkitan bilangan acak.
import pandas as pd # digunakan untuk memberikan label terkait data yang digunakan, dan digunakan untuk membaca dataset
from sklearn.neighbors import KNeighborsClassifier # digunakan untuk memprediksi kelas atau nilai menggunakan metode KNN dari sebuah sampel berdasarkan mayoritas kelas atau nilai rata-rata dari k tetangga terdekatnya dalam ruang fitur.
from sklearn.model_selection import train_test_split  # Fungsi ini digunakan untuk membagi dataset menjadi subset pelatihan dan pengujian
from sklearn.model_selection import KFold, cross_validate #KFold digunakan untuk validasi silang yang membagi data menjadi k subset dengan ukuran yang sama
                                                        # cross_validate Fungsi ini melakukan validasi silang dengan secara berulang membagi data menjadi subset pelatihan dan pengujian

# Baca Dataset

In [4]:
# membaca dataset menggunakan library pandas
data = pd.read_csv('indian_liver_patient.csv', sep=',')
# untuk menampilkan 5 data pertama dalam dataset
data.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65       0              0.7               0.1                   187   
1   62       1             10.9               5.5                   699   
2   62       1              7.3               4.1                   490   
3   58       1              1.0               0.4                   182   
4   72       1              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

# Pemisahan Data untuk melakukan pemisahan antara Data latih dan Data Training

menentukan data latih

In [5]:

# AMBIL LABEL SETIAP BARIS
# iloc digunakan untuk melakukan indexing berdasarkan posisi numerik pada DataFrame.
# mengambil semua baris dari kolom terakhir dataset. Dalam konteks ini, [:,-1:] berarti mengambil semua baris (:) dari kolom terakhir (-1).
# Kemudian, metode .values digunakan untuk mengonversi hasil seleksi menjadi representasi array NumPy. 
# ravel() digunakan untuk meratakan array menjadi satu dimensi.
# variabel label artinya berisi array satu dimensi yang merupakan nilai-nilai dari kolom terakhir dataset.
# label, yang berisi array satu dimensi yang merupakan nilai-nilai dari kolom terakhir dataset.
label = data.iloc[:,-1:].values.ravel()
label

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2,
       2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1,
       2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2,

Pemisahan data Uji

In [6]:
# AMBIL FEATURE DATA
# pengertian kode iloc dibawah sama dengan penertian kode diatas terkait dengan melakukan indexing
# tapi perbedaan disini hanyalah metode label digunakan untuk mengambil kolom dari baris dan kolom terakhir dataset sedangkan Feature mengambil semua baris 
# dan kolom kecuali baris dan kolom terakhir.
# variabel feature, yang berisi array dua dimensi yang merupakan nilai-nilai dari semua kolom kecuali kolom terakhir dataset.
feature = data.iloc[:,:-1]
feature.values

array([[65.  ,  0.  ,  0.7 , ...,  6.8 ,  3.3 ,  0.9 ],
       [62.  ,  1.  , 10.9 , ...,  7.5 ,  3.2 ,  0.74],
       [62.  ,  1.  ,  7.3 , ...,  7.  ,  3.3 ,  0.89],
       ...,
       [52.  ,  1.  ,  0.8 , ...,  6.4 ,  3.2 ,  1.  ],
       [31.  ,  1.  ,  1.3 , ...,  6.8 ,  3.4 ,  1.  ],
       [38.  ,  1.  ,  1.  , ...,  7.3 ,  4.4 ,  1.5 ]])

In [7]:
# PEMBAGIAN DATA LATIH DAN DATA UJI SEBANYAK 80% UNTUK DATA LATIH 20% UNTUK DATA TEST
X_train, X_test, y_train, y_test = train_test_split(feature, label ,test_size=0.3)

In [8]:
# Menampilkan jumlah data Latih dan data Uji
print("Jumlah Data Latih:", len(X_train))
print("Jumlah Data Uji:", len(X_test))

Jumlah Data Latih: 405
Jumlah Data Uji: 174


# Pemodelan Dengan KNN

In [9]:
# PEMODELAN MENGGUNAKAN KNN dengaan menentukan nilai K = 3, 
# yang disimpan pada variable clf (Classifikasi)
clf = KNeighborsClassifier(n_neighbors=3)

# FITTING DATA TRAINING = Fungsi ini digunakan untuk melatih model menggunakan data training.
# Dengan menggunakan .fit(), model clf akan melatih dirinya sendiri menggunakan X_train sebagai fitur dan y_train sebagai target, sehingga dapat menghasilkan prediksi yang lebih baik pada data baru.
clf.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

# Prediksi Hasil

In [10]:
# Kode di bawah digunakan untuk melakukan prediksi dengan menggunakan model yang telah dilatih (clf) pada data uji (X_test).
pred = clf.predict(X_test)
pred

array([2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1],
      dtype=int64)

In [11]:
# digunakan untuk membuat DataFrame yang memuat kolom-kolom 'Y True' (label yang sebenarnya) dan 'Predict' (prediksi yang dihasilkan) dari data uji (y_test dan pred).
cols = {
    'Y True' : y_test,
    'Predict' : pred,
}

# kemudian mencetak hasil sehingga dapat membandingkan antara prediksi model dg nilai yang sebenarnya dalam data uji
print("Prediksi Yang Dihasilkan")
pd.DataFrame(cols)

Prediksi Yang Dihasilkan


Y True  Predict
0         2        2
1         1        1
2         2        1
3         1        1
4         1        2
..      ...      ...
169       1        1
170       2        2
171       1        1
172       1        1
173       1        1

[174 rows x 2 columns]

# Pengukuran Performance

In [12]:
# FOLD = 10 yg menerapkan teknik validasi silang dg 10 kelipatan, atau membagi dataset
kfold = KFold(n_splits=10)
# membuat list dibawah ini yg berisi tiga metrik yg akan dinilai yaitu = accuracy, precision, recall
scores = ['accuracy', 'precision', 'recall']
# kode dibawah melakukan evaluasi silang dg library yg sudah diimport diatas yaitu cross_validate
results = cross_validate(clf, X_test, y_test, cv=kfold, scoring=scores, return_train_score=True)
# kode dibawah berisi perintah membuat data frame result_data yang berisi hasil evaluasi
results_data = pd.DataFrame(results)
results_data

fit_time  score_time  test_accuracy  train_accuracy  test_precision  \
0  0.002994    0.008979       0.611111        0.801282        0.888889   
1  0.003029    0.003952       0.666667        0.820513        0.687500   
2  0.001996    0.003989       0.666667        0.826923        0.833333   
3  0.001999    0.003986       0.722222        0.788462        0.866667   
4  0.002002    0.003992       0.764706        0.796178        0.800000   
5  0.001962    0.003024       0.764706        0.789809        0.800000   
6  0.002026    0.003989       0.294118        0.808917        0.363636   
7  0.001992    0.002996       0.764706        0.808917        0.785714   
8  0.001536    0.003024       0.705882        0.777070        0.800000   
9  0.002026    0.002992       0.352941        0.840764        0.400000   

   train_precision  test_recall  train_recall  
0         0.824000     0.571429      0.919643  
1         0.835938     0.916667      0.938596  
2         0.863248     0.714286      0.901786  
3         0.818182     0.812500      0.900000  
4         0.813953     0.923077      0.929204  
5         0.822581     0.923077      0.902655  
6         0.837209     0.444444      0.923077  
7         0.828125     0.916667      0.929825  
8         0.813008     0.857143      0.892857  
9         0.848485     0.444444      0.957265

# Performance dari model KNN yg dibuat

In [13]:
print("PERFORMANCE MODEL KNN")

accuracy = results_data.test_accuracy.mean() * 100
precision = results_data.test_precision.mean() * 100
recall = results_data.test_recall.mean() * 100

print("Accuracy : %0.2f" % accuracy, "%")
print("Precision : %0.2f " % precision, "%")
print("Recall : %0.2f " % recall, "%")

PERFORMANCE MODEL KNN
Accuracy : 63.14 %
Precision : 72.26  %
Recall : 75.24  %


# Menyimpan model K-NN dengan Classifikasi dataset Liver Patient

In [15]:
# menyimpan model dg library Joblib
import joblib
joblib.dump (clf,'model_new2.pkl')


['model_new2.pkl']